"""Tools available to the ReAct agent.

Each function is decorated with @tool — LangChain uses the function name and
docstring as the tool name/description that the LLM sees when deciding which
tool to call. Keep docstrings clear: they directly affect agent behaviour.

Error handling: tools return error strings (never raise). The LLM reads the
error in context and can adapt (retry with different params or skip the source).
"""

import os
from datetime import datetime
from pathlib import Path

import trafilatura
from ddgs import DDGS
from langchain_core.tools import tool

from config import Settings

settings = Settings()


@tool
def web_search(query: str) -> str:
    """Search the web using DuckDuckGo. Returns a list of results with title, URL, and snippet for each.

    Args:
        query: The search query string.
    """
    try:
        results = DDGS().text(query, max_results=settings.max_search_results)
        if not results:
            return "No results found."
        # Format results as numbered list — structured text helps the LLM parse them
        formatted = []
        for i, r in enumerate(results, 1):
            formatted.append(
                f"{i}. Title: {r.get('title', 'N/A')}\n"
                f"   URL: {r.get('href', 'N/A')}\n"
                f"   Snippet: {r.get('body', 'N/A')}"
            )
        return "\n\n".join(formatted)
    except Exception as e:
        return f"Search error: {e}"


@tool
def read_url(url: str) -> str:
    """Fetch and extract the main text content from a web page. Use this to read full articles found via web_search.

    The result is truncated to avoid context overflow.

    Args:
        url: The full URL of the web page to read.
    """
    try:
        # 10s timeout prevents the agent from hanging on slow/unresponsive sites
        config = trafilatura.settings.use_config()
        config.set("DEFAULT", "DOWNLOAD_TIMEOUT", "10")
        downloaded = trafilatura.fetch_url(url, config=config)
        if downloaded is None:
            return f"Error: Could not fetch URL: {url}"
        text = trafilatura.extract(downloaded)
        if not text:
            return f"Error: Could not extract text from: {url}"
        # Context engineering: truncate long pages to keep LLM context window manageable
        if len(text) > settings.max_url_content_length:
            text = text[: settings.max_url_content_length] + "\n\n[... truncated]"
        return text
    except Exception as e:
        return f"Error reading URL: {e}"


@tool
def write_report(description: str, content: str) -> str:
    """Save a Markdown research report to a file in the output directory.

    The filename is auto-generated as: YYYY-MM-DD_HHMM_<description>.md

    Args:
        description: Short research topic description for the filename (e.g. 'rag_comparison', 'naive_vs_parent_child'). Use lowercase with underscores, no spaces.
        content: The full Markdown content of the report.
    """
    try:
        os.makedirs(settings.output_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")
        slug = description.strip().replace(" ", "_").lower()
        filename = f"{timestamp}_{slug}.md"
        # Prepend metadata line so readers know which model produced the report
        meta = f"> Generated by `{settings.model_name}` on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        filepath = os.path.join(settings.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(meta + content)
        return f"Report saved successfully to: {filepath}"
    except Exception as e:
        return f"Error saving report: {e}"


@tool
def list_reports() -> str:
    """List all previously saved research reports in the output directory.

    Returns filenames sorted by date (newest first). Use this to check what
    research has already been done before starting new work.
    """
    try:
        output = Path(settings.output_dir)
        if not output.exists():
            return "No reports found — output directory does not exist yet."
        files = sorted(output.glob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
        if not files:
            return "No reports found."
        return "\n".join(f"{i}. {f.name}" for i, f in enumerate(files, 1))
    except Exception as e:
        return f"Error listing reports: {e}"


@tool
def read_file(filename: str) -> str:
    """Read a previously saved report from the output directory.

    Use this to review past research, build on earlier findings, or update
    an existing report. Use list_reports first to see available files.

    Args:
        filename: The filename to read (e.g. '2026-03-15_1420_rag_comparison.md').
    """
    try:
        filepath = Path(settings.output_dir) / filename
        if not filepath.exists():
            return f"Error: File not found: {filename}"
        # Restrict reads to the output directory (no path traversal)
        if not filepath.resolve().is_relative_to(Path(settings.output_dir).resolve()):
            return "Error: Access denied — can only read files from the output directory."
        text = filepath.read_text(encoding="utf-8")
        if len(text) > settings.max_url_content_length:
            text = text[: settings.max_url_content_length] + "\n\n[... truncated]"
        return text
    except Exception as e:
        return f"Error reading file: {e}"
